package thecafeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AtpositionId generated by hbm2java
 */
@Embeddable
public class AtpositionId implements java.io.Serializable {

	private String employeeid;
	private String positionid;

	public AtpositionId() {
	}

	public AtpositionId(String employeeid, String positionid) {
		this.employeeid = employeeid;
		this.positionid = positionid;
	}

	@Column(name = "EMPLOYEEID", nullable = false, length = 7)
	public String getEmployeeid() {
		return this.employeeid;
	}

	public void setEmployeeid(String employeeid) {
		this.employeeid = employeeid;
	}

	@Column(name = "POSITIONID", nullable = false)
	public String getPositionid() {
		return this.positionid;
	}

	public void setPositionid(String positionid) {
		this.positionid = positionid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AtpositionId))
			return false;
		AtpositionId castOther = (AtpositionId) other;

		return ((this.getEmployeeid() == castOther.getEmployeeid()) || (this.getEmployeeid() != null
				&& castOther.getEmployeeid() != null && this.getEmployeeid().equals(castOther.getEmployeeid())))
				&& ((this.getPositionid() == castOther.getPositionid())
						|| (this.getPositionid() != null && castOther.getPositionid() != null
								&& this.getPositionid().equals(castOther.getPositionid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEmployeeid() == null ? 0 : this.getEmployeeid().hashCode());
		result = 37 * result + (getPositionid() == null ? 0 : this.getPositionid().hashCode());
		return result;
	}

}
