package thecafeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BilldetailId generated by hbm2java
 */
@Embeddable
public class BilldetailId implements java.io.Serializable {

	private String productid;
	private int billid;

	public BilldetailId() {
	}

	public BilldetailId(String productid, int billid) {
		this.productid = productid;
		this.billid = billid;
	}

	@Column(name = "PRODUCTID", nullable = false, length = 7)
	public String getProductid() {
		return this.productid;
	}

	public void setProductid(String productid) {
		this.productid = productid;
	}

	@Column(name = "BILLID", nullable = false)
	public int getBillid() {
		return this.billid;
	}

	public void setBillid(int billid) {
		this.billid = billid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BilldetailId))
			return false;
		BilldetailId castOther = (BilldetailId) other;

		return ((this.getProductid() == castOther.getProductid()) || (this.getProductid() != null
				&& castOther.getProductid() != null && this.getProductid().equals(castOther.getProductid())))
				&& (this.getBillid() == castOther.getBillid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProductid() == null ? 0 : this.getProductid().hashCode());
		result = 37 * result + this.getBillid();
		return result;
	}

}
