package thecafeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BooktableId generated by hbm2java
 */
@Embeddable
public class BooktableId implements java.io.Serializable {

	private int customerid;
	private int dinnertableid;
	private String employeeid;

	public BooktableId() {
	}

	public BooktableId(int customerid, int dinnertableid, String employeeid) {
		this.customerid = customerid;
		this.dinnertableid = dinnertableid;
		this.employeeid = employeeid;
	}

	@Column(name = "CUSTOMERID", nullable = false)
	public int getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(int customerid) {
		this.customerid = customerid;
	}

	@Column(name = "DINNERTABLEID", nullable = false)
	public int getDinnertableid() {
		return this.dinnertableid;
	}

	public void setDinnertableid(int dinnertableid) {
		this.dinnertableid = dinnertableid;
	}

	@Column(name = "EMPLOYEEID", nullable = false, length = 7)
	public String getEmployeeid() {
		return this.employeeid;
	}

	public void setEmployeeid(String employeeid) {
		this.employeeid = employeeid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BooktableId))
			return false;
		BooktableId castOther = (BooktableId) other;

		return (this.getCustomerid() == castOther.getCustomerid())
				&& (this.getDinnertableid() == castOther.getDinnertableid())
				&& ((this.getEmployeeid() == castOther.getEmployeeid())
						|| (this.getEmployeeid() != null && castOther.getEmployeeid() != null
								&& this.getEmployeeid().equals(castOther.getEmployeeid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCustomerid();
		result = 37 * result + this.getDinnertableid();
		result = 37 * result + (getEmployeeid() == null ? 0 : this.getEmployeeid().hashCode());
		return result;
	}

}
