package thecafeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Categoryproduct generated by hbm2java
 */
@Entity
@Table(name = "categoryproduct", catalog = "theshopcoffee")
public class Categoryproduct implements java.io.Serializable {

	private String categoryproductid;
	private String name;
	private Boolean isdelete;
	private Date updateat;
	private Set<Product> products = new HashSet<Product>(0);

	public Categoryproduct() {
	}

	public Categoryproduct(String categoryproductid) {
		this.categoryproductid = categoryproductid;
	}

	public Categoryproduct(String categoryproductid, String name, Boolean isdelete, Set<Product> products) {
		this.categoryproductid = categoryproductid;
		this.name = name;
		this.isdelete = isdelete;
		this.products = products;
	}

	@Id

	@Column(name = "CATEGORYPRODUCTID", unique = true, nullable = false, length = 7)
	public String getCategoryproductid() {
		return this.categoryproductid;
	}

	public void setCategoryproductid(String categoryproductid) {
		this.categoryproductid = categoryproductid;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	@Column(name = "ISDELETE")
	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "categoryproduct")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
