package thecafeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "theshopcoffee")
public class Employee implements java.io.Serializable {

	private String employeeid;
	private String name;
	private Boolean sex;
	private String phone;
	private String address;
	private String usename;
	private String password;
	private Date updateat;
	private Boolean isdelete;
	private Set<Bill> bills = new HashSet<Bill>(0);
	private Set<Atposition> atpositions = new HashSet<Atposition>(0);
	private Set<Exportbill> exportbills = new HashSet<Exportbill>(0);
	private Set<Register> registers = new HashSet<Register>(0);
	private Set<Importbill> importbills = new HashSet<Importbill>(0);
	private Set<Image> images = new HashSet<Image>(0);
	private Set<Booktable> booktables = new HashSet<Booktable>(0);
	private Set<Salary> salaries = new HashSet<Salary>(0);

	public Employee() {
	}

	public Employee(String employeeid) {
		this.employeeid = employeeid;
	}

	public Employee(String employeeid, String name, Boolean sex, String phone, String address, String usename,
			String password, Date updateat, Boolean isdelete, Set<Bill> bills, Set<Atposition> atpositions,
			Set<Exportbill> exportbills, Set<Register> registers, Set<Importbill> importbills, Set<Image> images,
			Set<Booktable> booktables, Set<Salary> salaries) {
		this.employeeid = employeeid;
		this.name = name;
		this.sex = sex;
		this.phone = phone;
		this.address = address;
		this.usename = usename;
		this.password = password;
		this.updateat = updateat;
		this.isdelete = isdelete;
		this.bills = bills;
		this.atpositions = atpositions;
		this.exportbills = exportbills;
		this.registers = registers;
		this.importbills = importbills;
		this.images = images;
		this.booktables = booktables;
		this.salaries = salaries;
	}

	@Id

	@Column(name = "EMPLOYEEID", unique = true, nullable = false, length = 7)
	public String getEmployeeid() {
		return this.employeeid;
	}

	public void setEmployeeid(String employeeid) {
		this.employeeid = employeeid;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SEX")
	public Boolean getSex() {
		return this.sex;
	}

	public void setSex(Boolean sex) {
		this.sex = sex;
	}

	@Column(name = "PHONE", unique = true, length = 11)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "ADDRESS")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "USENAME")
	public String getUsename() {
		return this.usename;
	}

	public void setUsename(String usename) {
		this.usename = usename;
	}

	@Column(name = "PASSWORD")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	@Column(name = "ISDELETE")
	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "employee")
	public Set<Bill> getBills() {
		return this.bills;
	}

	public void setBills(Set<Bill> bills) {
		this.bills = bills;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "employee")
	public Set<Atposition> getAtpositions() {
		return this.atpositions;
	}

	public void setAtpositions(Set<Atposition> atpositions) {
		this.atpositions = atpositions;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "employee")
	public Set<Exportbill> getExportbills() {
		return this.exportbills;
	}

	public void setExportbills(Set<Exportbill> exportbills) {
		this.exportbills = exportbills;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "employee")
	public Set<Register> getRegisters() {
		return this.registers;
	}

	public void setRegisters(Set<Register> registers) {
		this.registers = registers;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "employee")
	public Set<Importbill> getImportbills() {
		return this.importbills;
	}

	public void setImportbills(Set<Importbill> importbills) {
		this.importbills = importbills;
	}

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "employees")
	public Set<Image> getImages() {
		return this.images;
	}

	public void setImages(Set<Image> images) {
		this.images = images;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "employee")
	public Set<Booktable> getBooktables() {
		return this.booktables;
	}

	public void setBooktables(Set<Booktable> booktables) {
		this.booktables = booktables;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "employee")
	public Set<Salary> getSalaries() {
		return this.salaries;
	}

	public void setSalaries(Set<Salary> salaries) {
		this.salaries = salaries;
	}

}
