package thecafeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exportbilldetail generated by hbm2java
 */
@Entity
@Table(name = "exportbilldetail", catalog = "theshopcoffee")
public class Exportbilldetail implements java.io.Serializable {

	private ExportbilldetailId id;
	private Exportbill exportbill;
	private Materialdetail materialdetail;
	private Integer quantity;
	private Date updateat;
	private Boolean isdelete;

	public Exportbilldetail() {
	}

	public Exportbilldetail(ExportbilldetailId id, Exportbill exportbill, Materialdetail materialdetail) {
		this.id = id;
		this.exportbill = exportbill;
		this.materialdetail = materialdetail;
	}

	public Exportbilldetail(ExportbilldetailId id, Exportbill exportbill, Materialdetail materialdetail,
			Integer quantity, Date updateat, Boolean isdelete) {
		this.id = id;
		this.exportbill = exportbill;
		this.materialdetail = materialdetail;
		this.quantity = quantity;
		this.updateat = updateat;
		this.isdelete = isdelete;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "exportbillid", column = @Column(name = "EXPORTBILLID", nullable = false)),
			@AttributeOverride(name = "materialdetailid", column = @Column(name = "MATERIALDETAILID", nullable = false)) })
	public ExportbilldetailId getId() {
		return this.id;
	}

	public void setId(ExportbilldetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "EXPORTBILLID", nullable = false, insertable = false, updatable = false)
	public Exportbill getExportbill() {
		return this.exportbill;
	}

	public void setExportbill(Exportbill exportbill) {
		this.exportbill = exportbill;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MATERIALDETAILID", nullable = false, insertable = false, updatable = false)
	public Materialdetail getMaterialdetail() {
		return this.materialdetail;
	}

	public void setMaterialdetail(Materialdetail materialdetail) {
		this.materialdetail = materialdetail;
	}

	@Column(name = "QUANTITY")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	@Column(name = "ISDELETE")
	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

}
