package thecafeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ExportbilldetailId generated by hbm2java
 */
@Embeddable
public class ExportbilldetailId implements java.io.Serializable {

	private int exportbillid;
	private int materialdetailid;

	public ExportbilldetailId() {
	}

	public ExportbilldetailId(int exportbillid, int materialdetailid) {
		this.exportbillid = exportbillid;
		this.materialdetailid = materialdetailid;
	}

	@Column(name = "EXPORTBILLID", nullable = false)
	public int getExportbillid() {
		return this.exportbillid;
	}

	public void setExportbillid(int exportbillid) {
		this.exportbillid = exportbillid;
	}

	@Column(name = "MATERIALDETAILID", nullable = false)
	public int getMaterialdetailid() {
		return this.materialdetailid;
	}

	public void setMaterialdetailid(int materialdetailid) {
		this.materialdetailid = materialdetailid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExportbilldetailId))
			return false;
		ExportbilldetailId castOther = (ExportbilldetailId) other;

		return (this.getExportbillid() == castOther.getExportbillid())
				&& (this.getMaterialdetailid() == castOther.getMaterialdetailid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getExportbillid();
		result = 37 * result + this.getMaterialdetailid();
		return result;
	}

}
