package thecafeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Importbilldetail generated by hbm2java
 */
@Entity
@Table(name = "importbilldetail", catalog = "theshopcoffee")
public class Importbilldetail implements java.io.Serializable {

	private ImportbilldetailId id;
	private Importbill importbill;
	private Materialdetail materialdetail;
	private Date updateat;
	private Boolean isdelete;

	public Importbilldetail() {
	}

	public Importbilldetail(ImportbilldetailId id, Importbill importbill, Materialdetail materialdetail) {
		this.id = id;
		this.importbill = importbill;
		this.materialdetail = materialdetail;
	}

	public Importbilldetail(ImportbilldetailId id, Importbill importbill, Materialdetail materialdetail,
			Integer quantity, Date updateat, Boolean isdelete) {
		this.id = id;
		this.importbill = importbill;
		this.materialdetail = materialdetail;
		this.updateat = updateat;
		this.isdelete = isdelete;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "materialdetailid", column = @Column(name = "MATERIALDETAILID", nullable = false)),
			@AttributeOverride(name = "importbillid", column = @Column(name = "IMPORTBILLID", nullable = false)) })
	public ImportbilldetailId getId() {
		return this.id;
	}

	public void setId(ImportbilldetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IMPORTBILLID", nullable = false, insertable = false, updatable = false)
	public Importbill getImportbill() {
		return this.importbill;
	}

	public void setImportbill(Importbill importbill) {
		this.importbill = importbill;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MATERIALDETAILID", nullable = false, insertable = false, updatable = false)
	public Materialdetail getMaterialdetail() {
		return this.materialdetail;
	}

	public void setMaterialdetail(Materialdetail materialdetail) {
		this.materialdetail = materialdetail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	@Column(name = "ISDELETE")
	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

}
