package thecafeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Importbill generated by hbm2java
 */
@Entity
@Table(name = "importbill", catalog = "theshopcoffee")
public class Importbill implements java.io.Serializable {

	private int importbillid;
	private Employee employee;
	private Supplier supplier;
	private Date updateat;
	private Boolean isdelete;
	private Set<Importbilldetail> importbilldetails = new HashSet<Importbilldetail>(0);

	public Importbill() {
	}

	public Importbill(int importbillid) {
		this.importbillid = importbillid;
	}

	public Importbill(int importbillid, Employee employee, Supplier supplier, Date updateat, Boolean isdelete,
			Set<Importbilldetail> importbilldetails) {
		this.importbillid = importbillid;
		this.employee = employee;
		this.supplier = supplier;
		this.updateat = updateat;
		this.isdelete = isdelete;
		this.importbilldetails = importbilldetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IMPORTBILLID", unique = true, nullable = false)
	public int getImportbillid() {
		return this.importbillid;
	}

	public void setImportbillid(int importbillid) {
		this.importbillid = importbillid;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "EMPLOYEEID")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SUPPLIERID")
	public Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	@Column(name = "ISDELETE")
	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "importbill")
	public Set<Importbilldetail> getImportbilldetails() {
		return this.importbilldetails;
	}

	public void setImportbilldetails(Set<Importbilldetail> importbilldetails) {
		this.importbilldetails = importbilldetails;
	}

}
