package thecafeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Material generated by hbm2java
 */
@Entity
@Table(name = "material", catalog = "theshopcoffee")
public class Material implements java.io.Serializable {

	private int materialid;
	private String name;
	private String unit;
	private Date updateat;
	private Boolean isdelete;
	private Set<Materialdetail> materialdetails = new HashSet<Materialdetail>(0);

	public Material() {
	}

	public Material(int materialid) {
		this.materialid = materialid;
	}

	public Material(int materialid, String name, String unit, Date updateat, Boolean isdelete,
			Set<Materialdetail> materialdetails) {
		this.materialid = materialid;
		this.name = name;
		this.unit = unit;
		this.updateat = updateat;
		this.isdelete = isdelete;
		this.materialdetails = materialdetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MATERIALID", unique = true, nullable = false)
	public int getMaterialid() {
		return this.materialid;
	}

	public void setMaterialid(int materialid) {
		this.materialid = materialid;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "UNIT", length = 50)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	@Column(name = "ISDELETE")
	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "material")
	public Set<Materialdetail> getMaterialdetails() {
		return this.materialdetails;
	}

	public void setMaterialdetails(Set<Materialdetail> materialdetails) {
		this.materialdetails = materialdetails;
	}

}
