package thecafeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Position generated by hbm2java
 */
@Entity
@Table(name = "position", catalog = "theshopcoffee")
public class Position implements java.io.Serializable {

	private String positionid;
	private String name;
	private Date updateat;
	private Boolean isdelete;
	private Set<Atposition> atpositions = new HashSet<Atposition>(0);

	public Position() {
	}

	public Position(String positionid) {
		this.positionid = positionid;
	}

	public Position(String positionid, String name, Date updateat, Boolean isdelete, Set<Atposition> atpositions) {
		this.positionid = positionid;
		this.name = name;
		this.updateat = updateat;
		this.isdelete = isdelete;
		this.atpositions = atpositions;
	}

	@Id

	@Column(name = "POSITIONID", unique = true, nullable = false)
	public String getPositionid() {
		return this.positionid;
	}

	public void setPositionid(String positionid) {
		this.positionid = positionid;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	@Column(name = "ISDELETE")
	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "position")
	public Set<Atposition> getAtpositions() {
		return this.atpositions;
	}

	public void setAtpositions(Set<Atposition> atpositions) {
		this.atpositions = atpositions;
	}

}
