package thecafeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Price generated by hbm2java
 */
@Entity
@Table(name = "price", catalog = "theshopcoffee")
public class Price implements java.io.Serializable {

	private int priceid;
	private Product product;
	private Date startdatetime;
	private Date enddatetime;
	private Integer price;
	private Date updateat;
	private Boolean isdelete;

	public Price() {
	}

	public Price(int priceid) {
		this.priceid = priceid;
	}

	public Price(int priceid, Product product, Date startdatetime, Date enddatetime, Integer price, Date updateat,
			Boolean isdelete) {
		this.priceid = priceid;
		this.product = product;
		this.startdatetime = startdatetime;
		this.enddatetime = enddatetime;
		this.price = price;
		this.updateat = updateat;
		this.isdelete = isdelete;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PRICEID", unique = true, nullable = false)
	public int getPriceid() {
		return this.priceid;
	}

	public void setPriceid(int priceid) {
		this.priceid = priceid;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PRODUCTID")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "STARTDATETIME", length = 19)
	public Date getStartdatetime() {
		return this.startdatetime;
	}

	public void setStartdatetime(Date startdatetime) {
		this.startdatetime = startdatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ENDDATETIME", length = 19)
	public Date getEnddatetime() {
		return this.enddatetime;
	}

	public void setEnddatetime(Date enddatetime) {
		this.enddatetime = enddatetime;
	}

	@Column(name = "PRICE")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	@Column(name = "ISDELETE")
	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

}
