package thecafeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Salary generated by hbm2java
 */
@Entity
@Table(name = "salary", catalog = "theshopcoffee")
public class Salary implements java.io.Serializable {

	private int salaryid;
	private Employee employee;
	private Integer salaryonhour;
	private Date startdate;
	private Date enddate;
	private Date updateat;
	private Boolean isdelete;

	public Salary() {
	}

	public Salary(int salaryid) {
		this.salaryid = salaryid;
	}

	public Salary(int salaryid, Employee employee, Integer salaryonhour, Date startdate, Date enddate, Date updateat,
			Boolean isdelete) {
		this.salaryid = salaryid;
		this.employee = employee;
		this.salaryonhour = salaryonhour;
		this.startdate = startdate;
		this.enddate = enddate;
		this.updateat = updateat;
		this.isdelete = isdelete;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SALARYID", unique = true, nullable = false)
	public int getSalaryid() {
		return this.salaryid;
	}

	public void setSalaryid(int salaryid) {
		this.salaryid = salaryid;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "EMPLOYEEID")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "SALARYONHOUR")
	public Integer getSalaryonhour() {
		return this.salaryonhour;
	}

	public void setSalaryonhour(Integer salaryonhour) {
		this.salaryonhour = salaryonhour;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STARTDATE", length = 10)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENDDATE", length = 10)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	@Column(name = "ISDELETE")
	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

}
