package thecafeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name = "schedule", catalog = "theshopcoffee")
public class Schedule implements java.io.Serializable {

	private String scheduleid;
	private Date starttime;
	private Date endtime;
	private Float payrate;
	private Date updateat;
	private Boolean isdelete;
	private Set<Register> registers = new HashSet<Register>(0);

	public Schedule() {
	}

	public Schedule(String scheduleid) {
		this.scheduleid = scheduleid;
	}

	public Schedule(String scheduleid, Date starttime, Date endtime, Float payrate, Date updateat, Boolean isdelete,
			Set<Register> registers) {
		this.scheduleid = scheduleid;
		this.starttime = starttime;
		this.endtime = endtime;
		this.payrate = payrate;
		this.updateat = updateat;
		this.isdelete = isdelete;
		this.registers = registers;
	}

	@Id

	@Column(name = "SCHEDULEID", unique = true, nullable = false, length = 7)
	public String getScheduleid() {
		return this.scheduleid;
	}

	public void setScheduleid(String scheduleid) {
		this.scheduleid = scheduleid;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "STARTTIME", length = 8)
	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "ENDTIME", length = 8)
	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	@Column(name = "PAYRATE", precision = 12, scale = 0)
	public Float getPayrate() {
		return this.payrate;
	}

	public void setPayrate(Float payrate) {
		this.payrate = payrate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	@Column(name = "ISDELETE")
	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "schedule")
	public Set<Register> getRegisters() {
		return this.registers;
	}

	public void setRegisters(Set<Register> registers) {
		this.registers = registers;
	}

}
