package thecafeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "supplier", catalog = "theshopcoffee")
public class Supplier implements java.io.Serializable {

	private int supplierid;
	private String name;
	private String address;
	private String phone;
	private Date updateat;
	private Boolean isdelete;
	private Set<Importbill> importbills = new HashSet<Importbill>(0);

	public Supplier() {
	}

	public Supplier(int supplierid) {
		this.supplierid = supplierid;
	}

	public Supplier(int supplierid, String name, String address, String phone, Date updateat, Boolean isdelete,
			Set<Importbill> importbills) {
		this.supplierid = supplierid;
		this.name = name;
		this.address = address;
		this.phone = phone;
		this.updateat = updateat;
		this.isdelete = isdelete;
		this.importbills = importbills;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SUPPLIERID", unique = true, nullable = false)
	public int getSupplierid() {
		return this.supplierid;
	}

	public void setSupplierid(int supplierid) {
		this.supplierid = supplierid;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ADDRESS")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "PHONE", length = 7)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	@Column(name = "ISDELETE")
	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "supplier")
	public Set<Importbill> getImportbills() {
		return this.importbills;
	}

	public void setImportbills(Set<Importbill> importbills) {
		this.importbills = importbills;
	}

}
