package thecafeshop.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Voucher generated by hbm2java
 */
@Entity
@Table(name = "voucher", catalog = "theshopcoffee")
public class Voucher implements java.io.Serializable {

	private int voucherid;
	private String name;
	private Date startdatetime;
	private Date enddate;
	private Integer number;
	private Integer count;
	private float discount;
	private Date updateat;
	private Boolean isdelete;
	private Set<Bill> bills = new HashSet<Bill>(0);

	public Voucher() {
	}

	public Voucher(int voucherid) {
		this.voucherid = voucherid;
	}

	public Voucher(int voucherid, String name, Date startdatetime, Date enddate, Integer number, Integer count,
			float discount, Date updateat, Boolean isdelete, Set<Bill> bills) {
		this.voucherid = voucherid;
		this.name = name;
		this.startdatetime = startdatetime;
		this.enddate = enddate;
		this.number = number;
		this.count = count;
		this.discount = discount;
		this.updateat = updateat;
		this.isdelete = isdelete;
		this.bills = bills;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "VOUCHERID", unique = true, nullable = false)
	public int getVoucherid() {
		return this.voucherid;
	}

	public void setVoucherid(int voucherid) {
		this.voucherid = voucherid;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "STARTDATETIME", length = 19)
	public Date getStartdatetime() {
		return this.startdatetime;
	}

	public void setStartdatetime(Date startdatetime) {
		this.startdatetime = startdatetime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENDDATE", length = 10)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@Column(name = "NUMBER")
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	@Column(name = "COUNT")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Column(name = "DISCOUNT")
	public float getDiscount() {
		return this.discount;
	}

	public void setDiscount(float discount) {
		this.discount = discount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	@Column(name = "ISDELETE")
	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "voucher")
	public Set<Bill> getBills() {
		return this.bills;
	}

	public void setBills(Set<Bill> bills) {
		this.bills = bills;
	}

}
